### ISSUE TITLE
Feature request: DAG diff between two commits

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1297]
FIrst of all, thanks for this excellent Git UI - I find it extremely useful.

For my feature request, I think it would be useful to be able to see the diff between two different commits in the DAG

Work flow:

1) click a commit
2) ctrl-click a second commit

Then show the diff between these two commits in the Files window.  Not sure what to display in the Graph window, as these commits could be separated by a large number of other commits.

Also, probably want to prevent user from ctrl-clicking more than two different commits.

**Comment by davvid** [comment]
The latest version should already work this way. I made it so that the diff displays shows the full diff and the files display shows all the files that changed between the two commits.

It basically gives you a holistic diff in the DAG's inline diff viewer.

Please let me know if you're seeing otherwise. We've already added a lot of features for the upcoming v4.2.0 release so I'm mostly focusing on trying to catch any bugs I missed and improving performance where possible. This is one of the features that's included in the upcoming release.

**Comment by boxerab** [comment]
Thanks @davvid . I have the latest git version, and I actually see just blank diff window when I click on one commit and then control click on a second.

**Comment by davvid** [comment]
Hold shift when selecting the other commit to add to the selection.

This applies to the list view as well, but it'll also select all of the intermediate commits which you may not want to do. The list view also lets you use Alt-click to add just that commit to the selection.

Those are the usual interactions for selection in list widgets. Once two items (or more, but the intermediates are ignored) are selected then cola will diff between the endpoints.

**Comment by davvid** [comment]
Sorry about that, I confused myself. I messed something up in the most recent tweaks, I'll be looking at this shortly.

**Comment by davvid** [comment]
I think the behavior should be better now. The graph and tree views now let you multi-select, and that multi-selection will control which two commits are diffed.

Don't use ctrl-click for this feature -- this interacts with the alt-click and shift-click/drag selection behavior. 

It works with the usual keyboard interactions as well. If you hold shift while pressing down it'll start to include that commit in its diff.

If you select more than 2 commits then it'll show the diffs for just the endpoints, by design. Hope that helps. Please try the latest commit, I fixed up the order-dependent-ness to it by sorting commits by their generation.

**Comment by boxerab** [comment]
Thanks. I am running gnome on Fedora 37.  I pulled the latest and installed.
alt-click selects nothing, but ctrl-click does select, except it is still not correct.

Also, with shift, if I select two consecutive commits, then diff is empty - should it not be the regular diff from selecting the newer commit ?

**Comment by davvid** [comment]
I'll switch over to testing on Debian/testing now. I was testing on a macos laptop.

When two commits A and B are selected then we basically show `git diff A~ B` which means "diff the parent of A against B". This ends up showing the totality of diffs produced by A and B.

If the two consecutive commits you selected were, for example, a regular commit followed by a Revert then the diff would be empty. But, I'm going to assume that this is not what you're seeing.

I did add some logic so that commits get sorted by their "generation", which should prevent us from showing incorrect or reverse diffs, but I'll test that a a little more closely.

Are the two commits available in a public repo I can test out? When you select, are you selecting from the graph viewer or the list widget?

I'm wondering if I missed a spot where the sorting needs to happen. I did see empty diffs as well which is what led to [4e7f111](https://github.com/git-cola/git-cola/commit/4e7f11187f760b1597f39c0af7eaf8367c52d37a) so if you could share how you got it to happen then that would be much appreciated.

**Comment by davvid** [comment]
I just tested on Linux. The modifiers are different on Linux.

You should be able to ctrl-click to add to the selection in both the Tree and List widgets when running on Linux. ctrl-click adds/removes from the selection.

Here's a few different ways to do it (on Linux)


Select one and then add to the selection in the List view:

1. regular click on an entry in the list view
2. ctrl-click on any other entry in the list view. This adds to the selection


Drag-select in the graph view

1. click and drag in the graph view to select a node
2. while holding ctrl, click and drag again to select another node. This adds it to the selection


Click select in the graph view

1. Select a node in the graph view
2. ctrl-click a 2nd node to add to the selection


Shift select to select multiple nodes in the list view

1. click on an entry in the list view
2. hold shift and click on any other entry in the list view. This adds to the selection and selects all the intermediate commits as well.



All of the above should be working. You don't need to right-click. It's all just based on the selection. Please let me know if you're seeing otherwise, and let me know if you're testing 4e7f111 or newer (`git rev-parse HEAD` will show your current git version).

**Comment by boxerab** [comment]
Thanks - I have the latest HEAD. The diff view works well now with multiple selections.

May I ask why you don't update the files view to match the diff ? This will give a summary of the files changed between two commits, and then it's possible to easily see changes to an individual file.

**Comment by davvid** [comment]
That was an oversight -- I had to update the filelist widget to also use the same ordered commits. The file list should work as expected now too.

**Comment by boxerab** [comment]
excellent - now it is a pleasure to use the DAG with multiple selections.
