### ISSUE TITLE
Git Cola does not honour desktop environment proxy settings on GNU+Linux operating systems

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#1420]
Dear maintainer(s),

Currently, the ~~only~~ way to make Git remote operations work in Git Cola under GNU+Linux operating systems is to launch Git Cola with the following environment variables set:

* `http_proxy`
* `https_proxy`

which requires users to hardcode the environment variables in their user profile to avoid the necessity of launching the application in a text terminal. It is inconvenient in contexts where the requirement of proxy settings may change depending on the network environment the user is currently in as the user needs to:

1. Change their environment variable settings in their user profile.
2. Log out their user session
3. Re-log in their user session

to make remote operations work again in Git Cola.

The situation can be improved if Git Cola can detect and honor the proxy settings set in the graphical interface of each desktop environment, where:

* in GNOME-based desktop environments, via the following GSettings keys:
    + `org.gnome.system.proxy`
    + `org.gnome.system.proxy.http`
    + `org.gnome.system.proxy.https`
* in the KDE desktop environment, via the following Kconfig:
    + kioslaverc/Proxy Settings/ProxyType
    + kioslaverc/Proxy Settings/httpProxy
    + kioslaverc/Proxy Settings/httpsProxy

The value of these settings may be accessed using the following external commands:

* `gsettings`
* `kreadconfig5`

**Comment by davvid** [comment]
Intriguing, thank you for the implementation notes. From what I understand it looks like we could handle the auto-configuration by setting these environment variables on the user's behalf. That's what you're suggesting, correct?

I have an additional idea ~ what do think about this?

We could have the GUI interaction present an exclusive choice between these three options:

```
Proxy Configuration
* Auto (default)
* Custom Proxy using http.proxy
* Disabled
```

The "Auto" mode would query gsettings/kreadconfig5 and if something is configured it'd set the environment variables.

Complication: If Git's `http.proxy` is already configured it should probably not set the environment variables and report a warning message to the Console. The reason for this is that when that variable is configured it will override anything Git is doing.

The "Custom" mode would have a text input field where the user can enter a custom proxy configuration. This would map directly to git's built-in `http.proxy` configuration variable.

https://git-scm.com/docs/git-config/#Documentation/git-config.txt-httpproxy

The "Disabled" option would do nothing, as it does today.

That's one option. What do you think?


Another option might be simpler. Instead of three different modes, we could have a single checkbox and a text input field.

```
* :heavy_check_mark:  Detect Proxy Settings
* HTTP Proxy (text input field)
```

When "Detect Proxy Settings" is enabled then we'll query unless `http.proxy` is already configured. If it is, we'll warn with a suggestion to disable "Detect Proxy Settings".

"HTTP Proxy" would map to the `http.proxy` git configuration value. If it's configured this setting has the highest precedence according to git's docs.

We'd only set the environment variables in the narrow situation that "Detect Proxy Settings" is enabled, we're on the corresponding desktop environment, and `http.proxy` isn't already configured.

Emptying out the `http.proxy` field would cause the `http.proxy` git config variable to be unset.

This would be option 2. Which do you think is better? Any alternatives?

**Comment by davvid** [comment]
I can definitely see the niceties of having "Detect Proxy Settings" be opt-out (enabled by default) but I'm starting to question whether we would want that warning to be displayed at all

Maybe it'd better as an informational message, e.g. ("HTTP proxy configured via http.proxy: $url") when `http.proxy` is present. I like that better. It'd be silly to start warning users with existing `http.proxy` configuration when they haven't changed anything, but informing them that we are using that configuration is helpful.

Similarly, when the detection mode ends up activating configuration, we can display, "Proxy detection found $url: The http_proxy environment variable has been set in the environment." That way it'll be clear which of the methods is being used.

I'm personally leaning towards the simpler checkbox + text input field idea. I'm curious to hear your thoughts and opinions.

**Comment by brlin-tw** [comment]
> From what I understand it looks like we could handle the auto-configuration by setting these environment variables on the user's behalf. That's what you're suggesting, correct?

The auto-configuration workflow I currently imagined:

1. If Git's `http.proxy` is already configured, use Git's configuration(or as in Git Cola's preference settings).
1. If the user has specified the `http_proxy`/`https_proxy` environment variable, prefer them. (one-off proxy override)
1. If the operating system is GNU+Linux:
    + If the desktop environment is GNOME-based(the `XDG_CURRENT_DESKTOP` environment variable's value matches GNOME, and maybe a few others that are based on the GTK graphic toolkit...), check proxy settings in the Gsettings.
    + If the desktop environment is KDE(the `XDG_CURRENT_DESKTOP` environment variable's value matches KDE), check proxy settings in the Kconfig.
1. (Logic for non-Linux operating systems when applicable)
1. No proxy

> Which do you think is better? Any alternatives?

Option 2 is fine.

> Maybe it'd better as an informational message, e.g. ("HTTP proxy configured via http.proxy: $url") when http.proxy is present.

That would be ideal.

> I'm personally leaning towards the simpler checkbox + text input field idea. I'm curious to hear your thoughts and opinions.

I'd say go for it.

**Comment by davvid** [comment]
Please give this a test when you get a chance. I tested this myself under Gnome using mitmproxy https://github.com/mitmproxy/mitmproxy.

I configured the host to `localhost` and the port to `8080` with mitmproxy running and then observed that the http fetch and pull operations were going through the proxy.

**Comment by brlin-tw** [comment]
@davvid 

> Please give this a test when you get a chance. I tested this myself under Gnome using mitmproxy https://github.com/mitmproxy/mitmproxy.

I can verify that the proxy configuration works over [TetherFi](https://github.com/pyamsoft/tetherfi), thanks!

**Comment by brlin-tw** [comment]
One thing that can be improved is to detect system proxy settings before every remote operation(in contrast to, at launch), remote operations will no longer work if Git Cola is running while the user has changed the proxy settings.

**Comment by davvid** [comment]
I believe it should be re-querying the settings right before the remote operations are performed in the fetch, push and pull dialogs. I can re-test that to verify, but it should be working that way at least.

There might be a small handful of code paths that don't configure the proxy (namely the Branches tool's context menu actions) so that'll need some attention.

**Comment by brlin-tw** [comment]
@davvid 

> I believe it should be re-querying the settings right before the remote operations are performed in the fetch, push and pull dialogs. I can re-test that to verify, but it should be working that way at least.

That's what I understand from the code as well, but it isn't consistent with the test result... :man_shrugging: 

Should be easily reproducible by:

1. Start proxy service.
1. Configure system proxy settings.
1. Launch Git Cola.
1. Try remote operation(should succeed).
1. Stop proxy service.
1. Unconfigure system proxy settings.
1. Retry remote operation(should also succeed, but the operation timed out in practice).

**Comment by davvid** [comment]
Ah, I figured it out. kwargs is persistent global state, so we have to clear it to handle the case where we unconfigure things. Please give that a try.

**Comment by brlin-tw** [comment]
@davvid 

> Please give that a try.

I have tried the d9d3a22 revision but the problem is still reproducible using the steps mentioned earlier.

**Comment by davvid** [comment]
Hmm, I'm not able to reproduce this on my side.

My test steps were:

* Launch proxy
* Launch ./bin/git-cola -r some/repo/with/http/urls
* Open Gnome's Settings app and go to the Network / Proxy page
  * Enable the "Network Proxy" toggle switch
  * Set the mode to "Manual".
    * Cola expects to see `manual` from `gsettings get org.gnome.system.proxy mode`.
    * What does that command output in your setup before/after configuring/re-configuring..
  * host = localhost, port = 8080 for both http and https
* shift-ctrl-f enter to fetch the repo
* Observe log output from proxy verifying the connection
-----
* Open Gnome's settings app and disable the "Network Proxy" toggle switch
* shift-ctrl-f enter in cola to fetch the repo
* Observe no log output from running proxy
-----
* Open Gnome's settings app and re-enable the "Network Proxy" toggle
* shift-ctrl-f enter in cola to fetch again
* Proxy log output is present again.
-----
* Repeat


I can start looking into adding status log messages so that we can get a hint about what code path it's hitting. That might shed some light on what's going on.

Questions that might help debug it:

* Is the output from `git config http.proxy` empty?
* Did you configure both http and https in the proxy settings? (I'm assuming "yes" otherwise it wouldn't work at all)
* Does it correct itself and follow the system settings after restarting cola?

**Comment by davvid** [comment]
I'll look into adding logging soon. I added one more tweak to ensure we clear data earlier, but that would have resulted in a traceback so I'm not sure if that's related.

This might be related and is something I just added:
* Do you have `http_proxy` and `https_proxy` already configured in your environment?

I just changed the behavior so that it retains these environment variables if you already have them defined. The logging should help make it clearer which scenario it's landing on. I hope that helps and I'll ping back here once the logging is ready in case that helps shed a light on what you're seeing.

**Comment by brlin-tw** [comment]
> Is the output from `git config http.proxy` empty?

Yes.

> What does gsettings get org.gnome.system.proxy mode output before/after re-configuring system settings?

Before:

```txt
'none'
```

After:

```txt
'manual'
```

> did you configure both http and https in the proxy settings?

[Yes.](https://gitlab.com/brlin/linux-proxy-configuration-helper/-/blob/3b4aa88729d0365223c6fca49b10b47074f1ac63/set-proxy.sh.source#L12-22)

> does it correct itself and follow the system settings after restarting cola?

No, see below.

> Do you have `http_proxy` and `https_proxy` already configured in your environment?

Generally no as I configure them on-demand in the text terminal(along with all the aforementioned desktop proxy settings) by using a set of scripts:

* [set-proxy.sh.source](https://gitlab.com/brlin/linux-proxy-configuration-helper/-/blob/3b4aa88729d0365223c6fca49b10b47074f1ac63/set-proxy.sh.source)
* [unset-proxy.sh.source](https://gitlab.com/brlin/linux-proxy-configuration-helper/-/blob/3b4aa88729d0365223c6fca49b10b47074f1ac63/unset-proxy.sh.source))

, this means that applications that are graphically launched from the desktop environment will not have the `*_proxy` environment variables set.

However, I made a mistake while verifying the patch previously as I launched Git Cola within the text terminal that has set the `*_proxy` environment variable, [which according to the spec I gave, should override the auto-detection logic](https://github.com/git-cola/git-cola/issues/1420#issuecomment-2370335500), therefore, will make Git Cola not reflect on desktop proxy setting changes.

Here's the full transcript of the text terminal while I was verifying the change(along with unrelated side project working progress of mine), just for reference:

<https://drive.google.com/file/d/1yyTjLUevCx6cnGagMXVkv4yXw11BErMc/view?usp=sharing>

That being said when I launched Git Cola without the `*_proxy` environment variables set(verified using the htop utility), Git Cola still didn't pick up the desktop proxy setting changes during remote operations, I'll test all the possible scenarios and report my findings here.

**Comment by brlin-tw** [comment]
# Test results(revison 81fc9a05)

## Configuration

### OS

Ubuntu 24.04

### Python

3.12.3 from Ubuntu 24.04

### Git

2.43.0

### Application launched from

Desktop environment app launcher, without `*_proxy` environment variables set.

### Proxy set in git config

False

### Desktop environment

GNOME

## Scenarios

Proxy settings are intentionally set to an invalid one(1.1.1.1:1111) to reduce test time.

### Proxy disabled → Git Cola launched → PULL → Proxy enabled → PULL

* First pull succeeded(should succeed)
* Second pull succeeded(should fail)

### Proxy enabled → Git Cola launched → PULL → Proxy disabled → PULL

* First pull succeeded (should fail)
* Second pull succeeded (should succeed)

**Comment by davvid** [comment]
I just added logging to the ctrl-0 (ctrl-zero) Console log window. You can right-click to clear the log and then run `shift-ctrl-f enter` to fetch. After you do a fetch and dismiss the window the output should contain something like this when the system proxy is enabled ~ it's displayed right before the "git fetch returned exit status 0" message:

```
2024-10-03 02:38:07:  http proxy configured from GNOME settings: localhost:8080
2024-10-03 02:38:07:  https proxy configured from GNOME settings: localhost:8080
2024-10-03 02:38:08:  "git fetch" returned exit status 0
```

Other messages that you may see as you adjust configuration:

```
http proxy configured by "git config http.proxy <url>"
http proxy configured by the "http_proxy" environment variable
```

If the autodetection doesn't configure anything then no log messages will appear.

Let's see if that ends up printing something unexpected (or nothing at all).

**Comment by brlin-tw** [comment]
@davvid

> nothing at all

Unfortunately, this is the case I am experiencing:

![Screenshot](https://github.com/user-attachments/assets/a94c2449-6e93-4af8-b5a2-74ec335cb527)

Revision: 247d6bf

**Comment by davvid** [comment]
I added one more log message. This log message is only on the `proxy` branch so you'll have to clone the repo and checkout the `proxy` branch to test it.

Please open the `git cola config` and ensure that the "Automatically Detect and Configure Proxy Settings" checkbox is enabled. The new log message is printed when the proxy feature is disabled by that setting. 

I originally considered this log message too noisy for users that opted-out of this feature ("silence is golden"), but if you think otherwise I can include this log message (despite the extra noise) in the main branch as well.

The following message will be logged when the proxy autodetection is disabled: `Proxy detection disabled by "git config cola.autodetectproxy false"`

The only remaining not-logged exit point from that function is when `XDG_CURRENT_DESKTOP` is not defined in the environment, but I'm pretty sure you should have that. You can `echo $XDG_CURRENT_DESKTOP` to verify that you have the value `GNOME` set in your environment to double-check, but I doubt that's the cause.

I hope it's this the `git config cola.autodetectproxy` setting. If not, then the only other explanation would be that it's not running with the latest code. If so, then read on, but only after trying the stuff above.

I was a little surprised by the pipx usage. I would almost recommend cloning the repo and running `/path/to/repos/git-cola/bin/git-cola` directly to guarantee that we're running the same version out of git. That said, that might just be my ignorance of pipx and things might work just fine there so feel free to try that as a last resort if the git config setting doesn't turn out to be fruitful.

Sharing the output from `env` and `git config --list && git config --global --list` could help me debug it, but you would probably want to do a scrub over the output first to remove any private information from it.

Thanks for patiently working through this, and please check the settings page to ensure that you have the new checkbox and HTTP Proxy URL configuration fields -- they're present in both the "Current Repository" and "All Repositories" tabs at the bottom.

**Comment by brlin-tw** [comment]
@davvid 

> The only remaining not-logged exit point from that function is when `XDG_CURRENT_DESKTOP` is not defined in the environment, but I'm pretty sure you should have that. You can `echo $XDG_CURRENT_DESKTOP` to verify that you have the value `GNOME` set in your environment to double-check, but I doubt that's the cause.

This is it!  The default Ubuntu desktop session has a different `XDG_CURRENT_DESKTOP` environment variable value:

```txt
$ printenv XDG_CURRENT_DESKTOP
ubuntu:GNOME
```

We probably should check whether it's KDE, then fallback to GNOME for all the Gtk-based desktop environments, what do you think?

**Comment by brlin-tw** [comment]
@davvid 
I can verify the proxy configuration is properly detected if I patch the `XDG_CURRENT_DESKTOP` matching logic:


> I would almost recommend cloning the repo and running /path/to/repos/git-cola/bin/git-cola directly to guarantee that we're running the same version out of git.

Got it, I'll check the source installation from now on.

> Sharing the output from env and git config --list && git config --global --list could help me debug it, but you would probably want to do a scrub over the output first to remove any private information from it.

[git config --list && git config --global --list](https://dpaste.com/9LQMR38AS)
[env](https://dpaste.com/GETH7CFKN)

> check the settings page to ensure that you have the new checkbox and HTTP Proxy URL configuration fields -- they're present in both the "Current Repository" and "All Repositories" tabs at the bottom.

Yes they are available in the interface.

**Comment by davvid** [comment]
Yay! Glad we sorted that out.

> We probably should check whether it's KDE, then fallback to GNOME for all the Gtk-based desktop environments, what do you think?

I think that's a great idea. I wonder whether the KDE  value is `ubuntu:KDE` on ubuntu? I'm on debian/testing (upstream from ubuntu) and the value is GNOME here (not debian:GNOME), so I wouldn't be surprised if it were `ubuntu:KDE`.

I'll go ahead and add a check for `xdg_current_desktop == 'KDE' or xdg_current_desktop.endswith(':KDE')` to handle all of the possibilities.

Awesome. I'll be pushing a commit to main shortly to get this working w/ the fallback to gnome/gtk/gsettings.
