### ISSUE TITLE
Git cola 10.1 requires python3-qtpy-pyqt6

### ISSUE THREAD

**Issue by francesco-gallo** [git-cola/git-cola#1444]
Hello, I don't know if it's intended or not, but the latest git-cola requires the python3-qtpy-pyqt6 package. not available on older distributions.

4.9.0 dependencies:  python3-polib, python3-qtpy, python3:any, git-core, libjs-jquery, libjs-underscore
4.10.1 dependencies:  python3-polib, python3-qtpy, python3:any, python3-qtpy-pyqt6, git-core, libjs-jquery, libjs-underscore

**Comment by davvid** [comment]
If this is on Debian, I wonder if you caught an in-progress update. I don't directly maintain the Debian packaging but I subscribe to bug reports from the Debian package. I did receive an email about them swapping dependencies around to accommodate the move to Qt6 in the last week or so.

This should resolve itself automatically as soon as the updated packages have been uploaded. FWIW, I am using Debian/testing and I was able to `sudo apt update && sudo apt install git-cola` and it upgraded me to the latest.

Please let me know if you're seeing otherwise.

**Comment by francesco-gallo** [comment]
I still see the pyqt6 requirement (I'm manually downloading the .deb from https://packages.debian.org/trixie/git-cola though...)
